spring:
  profiles: #실행환경(local(로컬),dev(개발),real(운영))
    active: local
      mvc:    view: #view 설정      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource: #DB 접속
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@211.63.89.70:1521:xe
    username: c##team03
    password: 1234
    hikari: #커넥션풀 구성
      connection-timeout: 30000
      maximum-pool-size: 10
      max-lifetime: 1800000
          messages: #메시지    basename: messages.validation
    encoding: UTF-8
      devtools:    livereload: #View reload      enabled: true
          restart: # 컨트롤러, 모델단이 바뀌었을 때 재시작      enabled: true
  servlet:    multipart: #파일업로드 설정      max-file-size: 50MB
      max-request-size: 50MB
#  security:#    oauth2:#      client:#        registration:#          naver:
#            client-id: p5qDyh8lEAltU8wkoV_r
#            client-secret: UgKq6J74t8
#            client-name: Naver
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/auth/naver/callback #{baseUrl}/{action}/oauth2/code/{registrationId}
#            #scope: name,email,profile_image
#          kakao:
#            client-id:  a8abdc39c132bcec49dcef03bb7a10d1
#            client-secret: UgKq6J74t8
#            client-name: Naver
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/auth/kakao/callback #{baseUrl}/{action}/oauth2/code/{registrationId}
#            #scope: name,email,profile_image
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response # 네이버가 회원정보를 json으로 넘겨주는데, response라는 키값으로 리턴해준다.
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id # 카카오가 회원정보를 json으로 넘겨주는데, id라는 키값으로 리턴해준다.          
            
          
mybatis: #mybatis 설정  type-aliases-package: kr.spring.**.vo
  mapper-locations: kr/spring/**/dao/*.xml
  
logging:  level: #로그 레벨 지정
    '[kr.spring]': debug
    
server:  port: 8080
  servlet:    context-path: /
    encoding:      charset: UTF-8
      enabled: true
      force: true

secret:
  key: nonasaja1234