--카트
  CREATE TABLE "C##TEAM03"."CART" 
   (	"CART_NUM" NUMBER NOT NULL ENABLE, 
	"MEM_NUM" NUMBER NOT NULL ENABLE, 
	"PRODUCT_NUM" NUMBER NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"REG_DATE" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CART_PK" PRIMARY KEY ("CART_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CART_FK1" FOREIGN KEY ("MEM_NUM")
	  REFERENCES "C##TEAM03"."MEMBER" ("MEM_NUM") ENABLE, 
	 CONSTRAINT "CART_FK2" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "C##TEAM03"."PRODUCT" ("PRODUCT_NUM") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;