--동호회

  CREATE TABLE "C##TEAM03"."CLUB_BOARD" 
   (	"CLUB_NUM" NUMBER NOT NULL ENABLE, 
	"CLUB_TITLE" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"CLUB_LEADER" NUMBER NOT NULL ENABLE, 
	"CLUB_CONTENT" CLOB NOT NULL ENABLE, 
	"CLUB_CODE" NUMBER(1,0) NOT NULL ENABLE, 
	"CLUB_LIMIT" NUMBER(3,0) DEFAULT 1 NOT NULL ENABLE, 
	"CLUB_PRE" NUMBER(3,0) DEFAULT 1 NOT NULL ENABLE, 
	"CLUB_HIT" NUMBER(6,0) DEFAULT 0 NOT NULL ENABLE, 
	"CLUB_MODIFY_DATE" DATE DEFAULT NULL, 
	"CLUB_REG_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CLUB_IMG" BLOB, 
	"CLUB_IMG_NAME" VARCHAR2(100 BYTE), 
	"CLUB_AGE" VARCHAR2(35 BYTE) DEFAULT NULL NOT NULL ENABLE, 
	"CLUB_GENDER" NUMBER DEFAULT NULL NOT NULL ENABLE, 
	"CLUB_RECRUIT" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"CLUB_DATE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"CLUB_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"CLUB_REGION" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CLUB_BOARD_PK" PRIMARY KEY ("CLUB_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CLUB_BOARD_FK1" FOREIGN KEY ("CLUB_LEADER")
	  REFERENCES "C##TEAM03"."MEMBER" ("MEM_NUM") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CLUB_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("CLUB_IMG") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;


--동호회 댓글
  
  CREATE TABLE "C##TEAM03"."CLUB_REPLY" 
   (	"REPLY_NUM" NUMBER NOT NULL ENABLE, 
	"CLUB_NUM" NUMBER NOT NULL ENABLE, 
	"MEM_NUM" NUMBER NOT NULL ENABLE, 
	"REPLY_CONTENT" VARCHAR2(900 BYTE) NOT NULL ENABLE, 
	"REPLY_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 CONSTRAINT "CLUB_REPLY_PK" PRIMARY KEY ("REPLY_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CLUB_REPLY_FK1" FOREIGN KEY ("CLUB_NUM")
	  REFERENCES "C##TEAM03"."CLUB_BOARD" ("CLUB_NUM") ENABLE, 
	 CONSTRAINT "CLUB_REPLY_FK2" FOREIGN KEY ("MEM_NUM")
	  REFERENCES "C##TEAM03"."MEMBER" ("MEM_NUM") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--동호회 대댓글
  
  CREATE TABLE "C##TEAM03"."CLUB_REREPLY" 
   (	"REREPLY_NUM" NUMBER NOT NULL ENABLE, 
	"REPLY_NUM" NUMBER NOT NULL ENABLE, 
	"CLUB_NUM" NUMBER NOT NULL ENABLE, 
	"MEM_NUM" NUMBER NOT NULL ENABLE, 
	"REREPLY_CONTENT" VARCHAR2(900 BYTE) NOT NULL ENABLE, 
	"REREPLY_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 CONSTRAINT "CLUB_REREPLY_PK" PRIMARY KEY ("REREPLY_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CLUB_REREPLY_FK1" FOREIGN KEY ("CLUB_NUM")
	  REFERENCES "C##TEAM03"."CLUB_BOARD" ("CLUB_NUM") ENABLE, 
	 CONSTRAINT "CLUB_REREPLY_FK2" FOREIGN KEY ("MEM_NUM")
	  REFERENCES "C##TEAM03"."MEMBER" ("MEM_NUM") ENABLE, 
	 CONSTRAINT "CLUB_REREPLY_FK3" FOREIGN KEY ("REPLY_NUM")
	  REFERENCES "C##TEAM03"."CLUB_REPLY" ("REPLY_NUM") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

