
  CREATE TABLE "C##TEAM03"."COMMUNITY_BOARD" 
   (	"COMMU_NUM" NUMBER NOT NULL ENABLE, 
	"COMMU_TITLE" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
	"MEM_NUM" NUMBER NOT NULL ENABLE, 
	"COMMU_CONTENT" CLOB NOT NULL ENABLE, 
	"COMMU_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"COMMU_MODIFY_DATE" DATE, 
	"COMMU_CODE" NUMBER(1,0) NOT NULL ENABLE, 
	"COMMU_RECOMMEND" NUMBER(6,0) DEFAULT 0 NOT NULL ENABLE, 
	"COMMU_HIT" NUMBER(6,0) DEFAULT 0 NOT NULL ENABLE, 
	"REGION" VARCHAR2(100 BYTE), 
	 CONSTRAINT "COMMUNITY_PK" PRIMARY KEY ("COMMU_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "COMMUNITY_FK1" FOREIGN KEY ("MEM_NUM")
	  REFERENCES "C##TEAM03"."MEMBER" ("MEM_NUM") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("COMMU_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

