
  CREATE TABLE "C##TEAM03"."LIONPOINT" 
   (	"POINT_NUM" NUMBER NOT NULL ENABLE, 
	"MEM_NUM" NUMBER NOT NULL ENABLE, 
	"LIONPOINT" NUMBER(8,0) NOT NULL ENABLE, 
	"CASH" NUMBER(8,0) NOT NULL ENABLE, 
	"REMAIN" NUMBER(8,0) NOT NULL ENABLE, 
	"ORDER_NUM" NUMBER, 
	"REG_DATE" DATE NOT NULL ENABLE, 
	 CONSTRAINT "POINT_PK" PRIMARY KEY ("POINT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "POINT_FK1" FOREIGN KEY ("MEM_NUM")
	  REFERENCES "C##TEAM03"."MEMBER" ("MEM_NUM") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

