--상품
CREATE TABLE "C##TEAM03"."PRODUCT" 
   (	"PRODUCT_NUM" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	"KIND" NUMBER(1,0) NOT NULL ENABLE, 
	"SUB_CATEGORY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"PRICE1" NUMBER(6,0) NOT NULL ENABLE, 
	"PRICE2" NUMBER(6,0) NOT NULL ENABLE, 
	"QUANTITY" NUMBER(6,0) NOT NULL ENABLE, 
	"REQ_QUANTITY" NUMBER(5,0) NOT NULL ENABLE, 
	"PHOTO1" BLOB NOT NULL ENABLE, 
	"PHOTO2" BLOB, 
	"PHOTO3" BLOB, 
	"COMPANY" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"ORIGIN" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"STATUS" NUMBER(1,0) NOT NULL ENABLE, 
	"DEADLINE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"REG_DATE" DATE NOT NULL ENABLE, 
	"MODIFY_DATE" DATE, 
	"PHOTO1_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"PHOTO2_NAME" VARCHAR2(100 BYTE), 
	"PHOTO3_NAME" VARCHAR2(100 BYTE), 
	"QUANTITY_DETAIL" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"EXP_DATE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"STORAGE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CUS_PHONE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DETAIL" CLOB NOT NULL ENABLE, 
	"DIV_QUANTITY" VARCHAR2(60 BYTE), 
	 CONSTRAINT "PRODUCT_PK" PRIMARY KEY ("PRODUCT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PHOTO1") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PHOTO2") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PHOTO3") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("DETAIL") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

