--주문상세
  CREATE TABLE "C##TEAM03"."NORDER_DETAIL" 
   (	"DETAIL_NUM" NUMBER NOT NULL ENABLE, 
	"PRODUCT_NUM" NUMBER NOT NULL ENABLE, 
	"PRODUCT_NAME" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	"PRODUCT_PRICE" NUMBER(6,0) NOT NULL ENABLE, 
	"PRODUCT_TOTAL" NUMBER(8,0) NOT NULL ENABLE, 
	"ORDER_QUANTITY" NUMBER(5,0) NOT NULL ENABLE, 
	"ORDER_NUM" NUMBER NOT NULL ENABLE, 
	"WAIT_STATUS" NUMBER(1,0) NOT NULL ENABLE, 
	 CONSTRAINT "NORDER_DETAIL_PK" PRIMARY KEY ("DETAIL_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "NORDER_DETAIL_FK" FOREIGN KEY ("ORDER_NUM")
	  REFERENCES "C##TEAM03"."NORDER" ("ORDER_NUM") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

