
  CREATE TABLE "C##TEAM03"."USED_BOARD" 
   (	"USED_NUM" NUMBER NOT NULL ENABLE, 
	"MEM_NUM" NUMBER NOT NULL ENABLE, 
	"TITLE" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
	"CONTENT" CLOB NOT NULL ENABLE, 
	"KIND" NUMBER(1,0) NOT NULL ENABLE, 
	"PRICE" NUMBER(6,0) DEFAULT 0 NOT NULL ENABLE, 
	"STATUS" NUMBER(1,0) NOT NULL ENABLE, 
	"CATEGORY" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"TRADE" VARCHAR2(30 BYTE), 
	"REG_DATE" DATE NOT NULL ENABLE, 
	"MODIFY_DATE" DATE, 
	"HIT" NUMBER(6,0) DEFAULT 0 NOT NULL ENABLE, 
	"FILENAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"UPLOADFILE" BLOB NOT NULL ENABLE, 
	"REGION" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "USED_BOARD_PK" PRIMARY KEY ("USED_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "USED_BOARD_FK1" FOREIGN KEY ("MEM_NUM")
	  REFERENCES "C##TEAM03"."MEMBER" ("MEM_NUM") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("UPLOADFILE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

